#!/usr/bin/expect -f

set prompt "#"
set address "2C:41:A1:81:B5:62"

spawn sudo bluetoothctl
expect -re $prompt
send "power on\r"
sleep 1
expect -re $prompt
send "scan on\r"
send_user "\nSleeping\r"
sleep 5
send_user "\nDone sleeping\r"
send "scan off\r"
expect "Controller"
send "trust $address\r"
sleep 2
send "connect $address\r"
sleep 2
send "0000\r"
sleep 3
send_user "\nShould be paired now.\r"
send "quit\r"
expect eof
